### ISSUE TITLE
showOnce not working

### ISSUE THREAD

**Issue by mdennis10** [florent37/TutoShowcase#14]
I'm using showOnce("key") but the animation is still running every time the application opens

     TutoShowcase.from(this)
                .on(R.id.preapproveTxtVw)
                .displaySwipableLeft()
                .animated(true)
                .delayed(300)
                .duration(2000)
                .show()
                .showOnce("key");

**Comment by mdennis10** [comment]
I was using the library incorrectly

**Comment by rohankandwal** [comment]
Show once is not working for me too. Using library v1.0.1, I checked out the code, the library is saving key into the SharedPreferences but not using it. 
  ```

 TutoShowcase.from(this)
            .showOnce("RestaurantListActivity")
      .setContentView(R.layout.view_tuto_restaurant_list)
      .withDismissView(R.id.tvOk)
      .on(R.id.ivSearch) //a view in actionbar
      .addCircle()
      .onClickContentView(R.id.rlIntroParent, null).show();
  }
```
