### ISSUE TITLE
how to use it on Recycler view

### ISSUE THREAD

**Issue by Xaus** [florent37/TutoShowcase#22]
i'm using recycler view in a fragment in my app and i need to say something about first recyclerview item
using this code :
```
TutoShowcase.from(getActivity())
            .setContentView(R.layout.tuto)
            .on(recyclerView.getChildAt(1))
            .addCircle()
            .show();

```
but when i use "recyclerView.getChildAt(1)"
returns me this error  : 

> java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewTreeObserver android.view.View.getViewTreeObserver()' on a null object reference

what can i do about this ?
thank's

**Comment by adnxy** [comment]
Same issue @florent37 could you assist please?

**Comment by florent37** [comment]
```recyclerView.getChildAt(1) may be null directly, can you use a handle to try ?

recyclerView.postDelayed(new Runnable(){
public void run(){
     TutoShowcase.from(getActivity())
            .setContentView(R.layout.tuto)
            .on(recyclerView.getChildAt(1))
            .addCircle()
            .show();

}
});```

**Comment by Xaus** [comment]
Nice Thank you
