### ISSUE TITLE
Provide default layouts

### ISSUE THREAD

**Issue by marbat87** [florent37/TutoShowcase#4]
Hi,

It would be very nice including some default layouts in the library, to use with:
`TutoShowcase.from(this)
    .setContentView(R.layout.tuto_sample)`

Thanks & Regards,
Marcello

**Comment by florent37** [comment]
why, it would have default texts & icons, it's not very useful

**Comment by marbat87** [comment]
Well, the library should include the ability to set text and image on default layouts ;)

**Comment by florent37** [comment]
why ? :)

**Comment by marbat87** [comment]
Because, if an application has 30 (for example) TutoShowcase pages to show... a default layout would be nice :) Don 't you agree?

**Comment by Damore** [comment]
Yes, it would make life easier with default layout, where it would be possible to just change the text for example. My case is where I have 20 examples of TutoShowcase and I have created 20 layouts and all the 20 has the same design, the only thing that changes is the text inside it.
