### ISSUE TITLE
Show the ShowcaseView Once

### ISSUE THREAD

**Issue by kennyung6** [florent37/TutoShowcase#8]
Hi florent, Great job on this library, it really simplifies creating showcase views. However, is there any feature in this library where the showcase view can be shown once after the first launch!

Regards

**Comment by florent37** [comment]
yes, `.showOnce("key")`

**Comment by kennyung6** [comment]
Thanks

KennY DexteR

On Wed, Sep 7, 2016 at 11:58 AM, Florent CHAMPIGNY <notifications@github.com

**Comment by mdennis10** [comment]
I'm using showOnce("key") but the animation is still running every time the application opens

         TutoShowcase.from(this)
                    .on(R.id.preapproveTxtVw)
                    .displaySwipableLeft()
                    .animated(true)
                    .delayed(300)
                    .duration(2000)
                    .show()
                    .showOnce("key");
